[package]
name = "tinyard"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
nalgebra = "0.33.2"
num-traits = "0.2.19"
simba = "0.9.0"

[features]
default = ["hessian"]
hessian = []
